- id: fractal-lint
  name: fractal-lint
  entry: fractal-lint
  language: python
  types_or: [c, c++]
  description: Custom style linter for ZKX

- id: fractal-commit-lint
  name: fractal-commit-lint
  entry: fractal-commit-lint
  language: python
  always_run: true
  stages: [commit-msg]
  description: Commit message linter enforcing Conventional Commits

- id: fractal-build-lint
  name: fractal-build-lint
  entry: fractal-build-lint --fix
  language: python
  files: (BUILD\.bazel|BUILD)$
  description: BUILD.bazel linter enforcing target sorting and naming
